FROM golang:1.20-alpine AS builder

RUN apk update && apk add make

COPY . /app/

WORKDIR /app
RUN make archmark-worker

FROM debian:bullseye

COPY --from=builder /app/archmark-worker /bin/archmark-worker

RUN apt update && apt install -y wget

RUN wget https://github.com/Y2Z/monolith/releases/download/v2.8.1/monolith-gnu-linux-aarch64 -O /bin/monolith
RUN chmod 0755 /bin/monolith
ENV MONOLITH_PATH=/bin/monolith

CMD ["/bin/archmark-worker"]
