version: "3.9"
services:
  web:
    image: docker.io/sparkymat/archmark:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data/archive:/data
    environment:
      JWT_SECRET: foobar
      SESSION_SECRET: foobar
      DATABASE_NAME: archmark
      DATABASE_HOSTNAME: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: foobar
      DATABASE_PORT: 5432
      DATABASE_SSL_MODE: false
      DOWNLOAD_PATH: /data
      FAKTORY_URL: "tcp://faktory:7419"
    links:
      - faktory
      - db
    depends_on:
      db:
        condition: service_healthy
  worker:
    image: docker.io/sparkymat/archmark-worker:latest
    volumes:
      - ./data/archive:/data
    environment:
      JWT_SECRET: foobar
      SESSION_SECRET: foobar
      DATABASE_NAME: archmark
      DATABASE_HOSTNAME: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: foobar
      DATABASE_PORT: 5432
      DATABASE_SSL_MODE: false
      ADMIN_PASSWORD: foobar
      DOWNLOAD_PATH: /data
      FAKTORY_URL: "tcp://faktory:7419"
    links:
      - faktory
      - db
      - web
  db:
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: foobar
      POSTGRES_DB: archmark
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  faktory:
    image: contribsys/faktory
    ports:
      - "7420:7420"
    volumes:
      - ./data/faktory:/var/lib/faktory
