on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
      - name: go test
        run: |
          go test ./...
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push web app
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sparkymat/archmark:latest
      - name: Build and push worker
        id: docker_build_worker
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile_worker
          push: true
          tags: sparkymat/archmark-worker:latest
