on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
      - name: go test
        run: |
          go test ./...
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sparkymat/archmark
          tag_with_ref: true
          tag_with_sha: true


